name: Julia Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.9.4'  
    - name: Instantiate and test
      run: |
        julia --project=@. -e 'using Pkg; Pkg.activate("."); Pkg.instantiate(); Pkg.test();'
